# Generated by Django 6.1.1 on 2026-09-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('loyalty_num', models.AutoField(primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=50)),
                ('discount_rate', models.FloatField(default=0.0)),
                ('multiplier_rate', models.FloatField(default=1.0)),
            ],
        ),
    ]
