# Generated by Django 6.1.1 on 2026-09-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('tel_no', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
    ]
