# Generated by Django 6.1.1 on 2026-09-29 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_guests', models.PositiveIntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('bk_date', models.DateField(auto_now_add=True)),
                ('bk_status', models.CharField(default='pending', max_length=20)),
                ('estimated_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.customer')),
            ],
        ),
    ]
