# Generated by Django 6.1.1 on 2026-09-30 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi_type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=30)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='hotel.booking')),
            ],
        ),
    ]
