# Generated by Django 6.1.1 on 2026-09-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_booking_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Item',
            fields=[
                ('booking_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotel.booking_item')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_items', to='hotel.room')),
            ],
            bases=('hotel.booking_item',),
        ),
    ]
