# Generated by Django 6.1.1 on 2026-09-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_activity_event_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Item',
            fields=[
                ('booking_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotel.booking_item')),
                ('no_of_guests', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_items', to='hotel.event')),
            ],
            bases=('hotel.booking_item',),
        ),
        migrations.CreateModel(
            name='Package_Item',
            fields=[
                ('booking_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotel.booking_item')),
                ('no_of_guests', models.PositiveIntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='hotel.packages')),
            ],
            bases=('hotel.booking_item',),
        ),
    ]
