# Generated by Django 6.1.1 on 2026-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_event_item_package_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('stay', 'Stay'), ('event', 'Event')], default='stay', max_length=10),
        ),
        migrations.AddField(
            model_name='packages',
            name='nights',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
