# Generated by Django 6.1.1 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_booking_booking_type_packages_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
