# Generated by Django 6.1.1 on 2026-10-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('stay', 'Stay'), ('event', 'Event'), ('activity', 'Activity')], default='stay', max_length=10),
        ),
        migrations.CreateModel(
            name='Activity_Item',
            fields=[
                ('booking_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotel.booking_item')),
                ('no_of_guests', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_items', to='hotel.activity')),
            ],
            bases=('hotel.booking_item',),
        ),
    ]
