# Generated by Django 6.1.1 on 2026-10-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_alter_booking_booking_type_activity_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='act_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
